image: "nginx:1.20.0"

ingress:
  host: chart-example.local
  annotations:
    kubernetes.io/ingress.class: nginx
ingresses:
  - host: chart-example.local
    annotations:
      kubernetes.io/ingress.class: nginx
  - host: another.local
    annotations:
      kubernetes.io/ingress.class: nginx

fullnameOverride: fullname-override
